export const HOME_BANNER_HEADING = "100+ actions for a\nlife well optimised lived";
export const HOME_BANNER_STRIKETHROUGH_WORD = "optimised";

export const HOME_SAMPLE_CARDS = [
  {
    id: "1",
    text: "Speak at 92 beats per minute.",
    frequency: "Weekly",
    frequencyCount: 2,
    authorName: "Peter Thornton",
    avatarColor: "#8B9BA8",
    category: "Find more focus",
    categories: ["Building disciplin", "Finding focus", "Reflecting", "Getting easy Wins", "Manifesting", "Practice visualisation"],
  },
  {
    id: "2",
    text: "If you can't decide, pretend you are deciding for a friend.",
    frequency: "Daily",
    frequencyCount: 5,
    authorName: "Naval Ravikant",
    avatarColor: "#A8B5C2",
    category: "Think clearly",
    categories: ["Building disciplin", "Finding focus", "Reflecting", "Getting easy Wins", "Manifesting", "Practice visualisation"],
  },
  {
    id: "3",
    text: "Write down three things you're grateful for before bed.",
    frequency: "Daily",
    frequencyCount: 8,
    authorName: "James Clear",
    avatarColor: "#B5C4B1",
    category: "Build good habits",
    categories: ["Building disciplin", "Finding focus", "Reflecting", "Getting easy Wins", "Manifesting", "Practice visualisation"],
  },
  {
    id: "4",
    text: "Take a 10-minute walk after every meal.",
    frequency: "Daily",
    frequencyCount: 3,
    authorName: "Andy Grove",
    avatarColor: "#C4B5A8",
    category: "Improve health",
    categories: ["Building disciplin", "Finding focus", "Reflecting", "Getting easy Wins", "Manifesting", "Practice visualisation"],
  },
  {
    id: "5",
    text: "Read one page before checking your phone in the morning.",
    frequency: "Daily",
    frequencyCount: 6,
    authorName: "Oliver Burkeman",
    avatarColor: "#B8A8C4",
    category: "Start well",
    categories: ["Building disciplin", "Finding focus", "Reflecting", "Getting easy Wins", "Manifesting", "Practice visualisation"],
  },
  {
    id: "6",
    text: "Schedule one hour of deep work before any meetings.",
    frequency: "Weekly",
    frequencyCount: 4,
    authorName: "Chris Sparks",
    avatarColor: "#A8C4B8",
    category: "Do deep work",
    categories: ["Building disciplin", "Finding focus", "Reflecting", "Getting easy Wins", "Manifesting", "Practice visualisation"],
  },
  {
    id: "7",
    text: "Put your phone in another room during dinner.",
    frequency: "Daily",
    frequencyCount: 7,
    authorName: "Shaan Puri",
    avatarColor: "#C4A8A8",
    category: "Be present",
    categories: ["Building disciplin", "Finding focus", "Reflecting", "Getting easy Wins", "Manifesting", "Practice visualisation"],
  },
  {
    id: "8",
    text: "Write a 200-word summary of what you learned this week.",
    frequency: "Weekly",
    frequencyCount: 3,
    authorName: "Adam Grant",
    avatarColor: "#A8BCC4",
    category: "Learn better",
    categories: ["Building disciplin", "Finding focus", "Reflecting", "Getting easy Wins", "Manifesting", "Practice visualisation"],
  },
  {
    id: "9",
    text: "Reply to all messages in two batches per day, not continuously.",
    frequency: "Daily",
    frequencyCount: 5,
    authorName: "Alex Brogan",
    avatarColor: "#C4C4A8",
    category: "Reduce distraction",
    categories: ["Building disciplin", "Finding focus", "Reflecting", "Getting easy Wins", "Manifesting", "Practice visualisation"],
  },
  {
    id: "10",
    text: "Plan your three most important tasks the night before.",
    frequency: "Daily",
    frequencyCount: 9,
    authorName: "James Clear",
    avatarColor: "#B5C4B1",
    category: "Work smarter",
    categories: ["Building disciplin", "Finding focus", "Reflecting", "Getting easy Wins", "Manifesting", "Practice visualisation"],
  },
  {
    id: "11",
    text: "Spend 5 minutes tidying one area of your home each morning.",
    frequency: "Daily",
    frequencyCount: 4,
    authorName: "Gurwinder Sparks",
    avatarColor: "#C4B8A8",
    category: "Create order",
    categories: ["Building disciplin", "Finding focus", "Reflecting", "Getting easy Wins", "Manifesting", "Practice visualisation"],
  },
  {
    id: "12",
    text: "Say no to one thing this week that doesn't align with your goals.",
    frequency: "Weekly",
    frequencyCount: 6,
    authorName: "Naval Ravikant",
    avatarColor: "#A8B5C2",
    category: "Set boundaries",
    categories: ["Building disciplin", "Finding focus", "Reflecting", "Getting easy Wins", "Manifesting", "Practice visualisation"],
  },
  {
    id: "13",
    text: "Send a message to someone you haven't spoken to in a while.",
    frequency: "Weekly",
    frequencyCount: 2,
    authorName: "Mel Sparks",
    avatarColor: "#C2A8B5",
    category: "Nurture relationships",
    categories: ["Building disciplin", "Finding focus", "Reflecting", "Getting easy Wins", "Manifesting", "Practice visualisation"],
  },
];

export const HOME_SELECTOR_FIELDS = [
  {
    name: "areas",
    placeholder: "Help me with everything",
    // label: "Life Area",
    options: [
      { value: "health", label: "Health & Fitness" },
      { value: "mind", label: "Mind & Focus" },
      { value: "relationships", label: "Relationships" },
      { value: "career", label: "Career & Work" },
      { value: "finance", label: "Finance" },
      { value: "creativity", label: "Creativity" },
    ],
  },
  {
    name: "authors",
    placeholder: "Suggested by anyone",
    options: [
      { value: "grove", label: "Andy Grove" },
      { value: "sparks", label: "Chris Sparks" },
      { value: "sparks", label: "Gurwinder Sparks" },
      { value: "sparks", label: "Mel Sparks" },
      { value: "ravikant", label: "Naval Ravikant" },
      { value: "grant", label: "Adam Grant" },
      { value: "burkeman", label: "Oliver Burkeman" },
      { value: "brogan", label: "Alex Brogan" },
      { value: "puri", label: "Shaan Puri" },
      { value: "clear", label: "James Clear" },
      
    ],
  },
  {
    name: "frequencies",
    placeholder: "That I can do anytime",
    options: [
      { value: "easy", label: "Easy" },
      { value: "moderate", label: "Moderate" },
      { value: "challenging", label: "Challenging" },
    ],
  },
];

export const HOME_INITIAL_VALUES = {
  areas: "",
  authors: "",
  frequencies: "",
};
