export { useState, type FormEvent } from "react";
export { useToast } from "@/context/ToastContext";

export {
  NEWSLETTER_HEADING,
  NEWSLETTER_BODY,
  NEWSLETTER_PLACEHOLDER,
  NEWSLETTER_BUTTON_TEXT,
  NEWSLETTER_CONSENT_TEXT,
  NEWSLETTER_TERMS_TEXT,
  NEWSLETTER_TERMS_HREF,
  NEWSLETTER_PRIVACY_TEXT,
  NEWSLETTER_PRIVACY_HREF,
} from "./constant";
