import { Goudy_Bookletter_1911, Quicksand } from "next/font/google";
import "./globals.css";

const goudyBookletter = Goudy_Bookletter_1911({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-goudy",
});

const quicksand = Quicksand({
  subsets: ["latin"],
  variable: "--font-quicksand",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html
      lang="en"
      className={`${goudyBookletter.variable} ${quicksand.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col max-w-360 mx-auto w-full bg-white">{children}</body>
    </html>
  );
}
